apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: RESPONSE_TEXT
          value: "Hello from Nginx"
        volumeMounts:
        - name: custom-nginx-config
          mountPath: /etc/nginx/templates
      volumes:
      - name: custom-nginx-config
        configMap:
          name: nginx-config
    serviceAccountName: test-eksec2-aws-load-balancer-controller
